// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NcaafPickEm.Infrastructure.Data;

#nullable disable

namespace NcaafPickEm.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921014305_Phase9_02_ExternalSubject")]
    partial class Phase9_02_ExternalSubject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NcaafPickEm.Domain.GameSets.GameSetRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ConferenceGamesOnly")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("RuleType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "Week", "SortOrder");

                    b.ToTable("GameSetRules", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.GameSets.WeekGameSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsesOverride")
                        .HasColumnType("bit");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Week")
                        .IsUnique();

                    b.HasIndex("LockAtUtc", "LockedUtc");

                    b.ToTable("WeekGameSets", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.GameSets.WeekGameSetGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<int?>("PointValueOverride")
                        .HasColumnType("int");

                    b.Property<string>("RemovedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ResolvedPointValue")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResultOverrideWinnerTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("SpreadAtLock")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<Guid>("WeekGameSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ResultOverrideWinnerTeamId");

                    b.HasIndex("WeekGameSetId", "GameId")
                        .IsUnique();

                    b.ToTable("WeekGameSetGames", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Leagues.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxUses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Uses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByMembershipId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Invites", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Leagues.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultPointValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("FirstWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("LastWeek")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SeasonYear");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Leagues.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayNameOverride")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("JoinedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("JoinedWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RemovedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "RemovedUtc");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique();

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Notifications.NotificationLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("LeagueId", "CreatedUtc")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "LeagueId", "Week", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationLog_WeeklyReminderOncePerWeek")
                        .HasFilter("[Type] IN (0, 1, 2)");

                    b.ToTable("NotificationLog", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Notifications.PushRetry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NotificationLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptUtc");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("NotificationLogId", "SubscriptionId")
                        .IsUnique();

                    b.ToTable("PushRetries", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Notifications.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("EndpointHash")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', [Endpoint]))", true);

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSuccessUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EndpointHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Operations.DataRefreshStatus", b =>
                {
                    b.Property<byte>("DataType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastSuccessUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DataType");

                    b.ToTable("DataRefreshStatus", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Operations.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc")
                        .IsDescending();

                    b.HasIndex("JobName", "ScheduledForUtc")
                        .IsUnique();

                    b.ToTable("JobRuns", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Operations.ProviderCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "StartedUtc");

                    b.ToTable("ProviderCalls", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Operations.UnmatchedGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<string>("RawAwayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawHomeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedUtc", "GameDate");

                    b.ToTable("UnmatchedGames", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Picks.Pick", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PickedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WeekGameSetGameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PickedTeamId");

                    b.HasIndex("WeekGameSetGameId");

                    b.HasIndex("MembershipId", "WeekGameSetGameId")
                        .IsUnique();

                    b.ToTable("Picks", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Picks.WeekSubmission", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WeekGameSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasUnseenGameChanges")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChangedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MembershipId", "WeekGameSetId");

                    b.HasIndex("WeekGameSetId");

                    b.ToTable("WeekSubmissions", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Points.PointRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte>("RuleType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("SpreadThreshold")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "Priority");

                    b.ToTable("PointRules", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Scoring.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorMembershipId");

                    b.HasIndex("LeagueId", "CreatedUtc")
                        .IsDescending(false, true);

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Scoring.SeasonStandingsSnapshot", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThroughWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("LeagueId", "ThroughWeek", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("SeasonStandingsSnapshots", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Scoring.WeekResult", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WeekGameSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveGameCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsWeekComplete")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("MembershipId", "WeekGameSetId");

                    b.HasIndex("WeekGameSetId");

                    b.ToTable("WeekResults", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Conference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CfbdId")
                        .HasColumnType("int");

                    b.Property<byte>("Classification")
                        .HasColumnType("tinyint");

                    b.Property<int?>("EspnGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CfbdId")
                        .IsUnique();

                    b.ToTable("Conferences", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CfbdGameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Clock")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<long?>("EspnEventId")
                        .HasColumnType("bigint");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsConferenceGame")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSaturdayEastern")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("KickoffEasternDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("KickoffUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastScoreUpdateUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Period")
                        .HasColumnType("tinyint");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Venue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CfbdGameId")
                        .IsUnique();

                    b.HasIndex("EspnEventId")
                        .IsUnique()
                        .HasFilter("[EspnEventId] IS NOT NULL");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("Status")
                        .HasFilter("[Status] IN (0, 1)");

                    b.HasIndex("SeasonYear", "Week", "IsSaturdayEastern");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.GameLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "FetchedUtc")
                        .IsDescending(false, true);

                    b.ToTable("GameLines", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Ranking", b =>
                {
                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<string>("Poll")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeasonYear", "Week", "Poll", "Rank");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonYear", "Week", "TeamId");

                    b.ToTable("Rankings", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.SeasonWeek", b =>
                {
                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRegularSeason")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SeasonYear", "Week");

                    b.ToTable("SeasonWeeks", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CfbdId")
                        .HasColumnType("int");

                    b.Property<byte>("Classification")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EspnTeamId")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Mascot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CfbdId")
                        .IsUnique();

                    b.HasIndex("Classification");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("EspnTeamId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.TeamAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Source", "Alias")
                        .IsUnique();

                    b.ToTable("TeamAliases", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalSubject")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NcaafPickEm.Domain.GameSets.GameSetRule", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conference");

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.GameSets.WeekGameSet", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.GameSets.WeekGameSetGame", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", null)
                        .WithMany()
                        .HasForeignKey("ResultOverrideWinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NcaafPickEm.Domain.GameSets.WeekGameSet", "WeekGameSet")
                        .WithMany()
                        .HasForeignKey("WeekGameSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("WeekGameSet");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Leagues.Invite", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.Membership", "CreatedByMembership")
                        .WithMany()
                        .HasForeignKey("CreatedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByMembership");

                    b.Navigation("League");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Leagues.League", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Leagues.Membership", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Notifications.NotificationLogEntry", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Notifications.PushSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NcaafPickEm.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Notifications.PushRetry", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Notifications.NotificationLogEntry", "NotificationLogEntry")
                        .WithMany()
                        .HasForeignKey("NotificationLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Notifications.PushSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationLogEntry");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Notifications.PushSubscription", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Picks.Pick", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "PickedTeam")
                        .WithMany()
                        .HasForeignKey("PickedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.GameSets.WeekGameSetGame", "WeekGameSetGame")
                        .WithMany()
                        .HasForeignKey("WeekGameSetGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("PickedTeam");

                    b.Navigation("WeekGameSetGame");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Picks.WeekSubmission", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.GameSets.WeekGameSet", "WeekGameSet")
                        .WithMany()
                        .HasForeignKey("WeekGameSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("WeekGameSet");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Points.PointRule", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conference");

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Scoring.AuditLogEntry", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.Membership", "ActorMembership")
                        .WithMany()
                        .HasForeignKey("ActorMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorMembership");

                    b.Navigation("League");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Scoring.SeasonStandingsSnapshot", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Leagues.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Scoring.WeekResult", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Leagues.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.GameSets.WeekGameSet", "WeekGameSet")
                        .WithMany()
                        .HasForeignKey("WeekGameSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("WeekGameSet");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Game", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.GameLine", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Ranking", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.Team", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("NcaafPickEm.Domain.Seasons.TeamAlias", b =>
                {
                    b.HasOne("NcaafPickEm.Domain.Seasons.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
